remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - untitled-1.md

footer: '<span id="datetime"></span><script>var dt = new Date();
document.getElementById("datetime").innerHTML=dt.toLocaleString();</script>'